<?php

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Table\AppritiatespostsTables;
use App\Model\Table\CategorysTables;
use App\Model\Table\ContactsTables;
use App\Model\Table\NotificationsTables;
use App\Model\Table\PostsTables;
use App\Model\Table\ProfilesTables;
use App\Model\Table\TrafficsTables;
use App\Model\Table\TransactionsTables;
use App\Model\Table\UsersTables;
use Cake\Datasource\ConnectionManager;
use Cake\ORM\TableRegistry;
use Cake\Routing\Router;
use Google_Client;
use mysql_xdevapi\Session;
use Cake\Network\Session\DatabaseSession;
use Cake\Mailer\Email;



class MainController extends AppController
{
    public $base_url;
    public $table;
    public $Users;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->base_url = Router::url("/", true);

    }

    public function removehtml($c)
    {
        $c = trim(preg_replace('/[\t\n\r\s]+/', ' ', $c));
        $c = substr($c, 0, 100);
        return $c = strip_tags($c);

    }

    function google($url)
    {

        $client = new Google_Client();
        $jsonpath = 'titanium-gantry-236611-014936a0a534.json';
// service_account_file.json is the private key that you created for your service account.
        $client->setAuthConfig($jsonpath);
        $client->addScope('https://www.googleapis.com/auth/indexing');

// Get a Guzzle HTTP Client
        $httpClient = $client->authorize();
        $endpoint = 'https://indexing.googleapis.com/v3/urlNotifications:publish';

// Define contents here. The structure of the content is described in the next step.
        $content = '{
            "url" : "'.$url.'",
            "type" : "URL_UPDATED"
        }';

//var_dump($content);exit;
        $response = $httpClient->post($endpoint, [ 'body' => $content ]);
        $status_code = $response->getStatusCode();

        $path = $this->base_url;
        // $file = fopen("success.txt", "a");
        //  fwrite($file, "Hello World. Testing!");

        if ($status_code == "200") {

            $file = fopen("success.txt", "a");
            fwrite($file, "Success! url".$url."\r\n");



        } else {
            $file = fopen("failure.txt", "a");
            fwrite($file, "Error url!".$url."Error code".$status_code."\r\n");



        }
        return $status_code;

    }

    public function index()
    {

        $data=array();
        $con = mysqli_connect("localhost","voteonl1_1","Shubhendu@12","voteonl1_wp586");

// Check connection
        if (mysqli_connect_errno()) {
            echo "Failed to connect to MySQL: " . mysqli_connect_error();
            exit();
        }


        $sql = "SELECT * FROM wpr7_posts where is_index='0' and post_type='post' ORDER BY id";

        if ($result = $con -> query($sql)) {
            while ($row = $result -> fetch_row()) {

                $id=$row[0];


                if (strpos($row[18], '?p') !== false) {



                    $sql2 = "SELECT * FROM wpr7_yoast_seo_links where target_post_id='$id' and type='internal' ";


                    if ($result2 = $con -> query($sql2)) {
                        while ($row2 = $result2 -> fetch_row()) {





                            if (strpos($row2[1], '?p') == false) {

                                array_push($data,$row2[1]);


                            }


                        }
                    }



                }else{
                    array_push($data,$row[18]);


                }



            }
            $result -> free_result();
        }
        var_dump(array_unique($data));


        foreach(array_unique($data) as $d){


            if (strpos($row2[1], 'lovetoreads.com') !== false) {

            }else{

                $ret= $this->google($d);
                // var_dump($d."<br/>");

                if($ret==200){
                    $sql="UPDATE wpr7_posts
SET is_index='1'
WHERE guid='".$d."' and post_type='post' ";
                    $con -> query($sql);



                    $sql24 = "SELECT * FROM wpr7_yoast_seo_links where url='$d' and type='internal' ";


                    if ($result24 = $con -> query($sql24)) {
                        while ($row24 = $result24 -> fetch_row()) {

                            $pid=$row24[3];
                            $sqle="UPDATE wpr7_posts
SET is_index='1'
WHERE ID='".$pid."' and post_type='post' ";
                            $con -> query($sqle);

                            echo $pid."<br/>";

                        }

                    }




                }

                echo $ret;

            }


        }
        var_dump("done");
        exit;

    }
}

?>